### ISSUE TITLE
mkdir throws error whether I have the folders or not

### ISSUE THREAD

**Issue by missmatsuko** [debute/laravel-mix-favicon#3]
When I run my build with this package, I got this error:
```
Error: ENOENT: no such file or directory, mkdir 'resources/favicon'
```

So I made the directory `resources/favicon` and ran again to get this error:
```
Error: EEXIST: file already exists, mkdir 'resources/favicon'
```

When I commented out these two `mkdir` sections (and already have the folders it tries to make), the build works:

https://github.com/debute/laravel-mix-favicon/blob/13013f6ce5ff003d5f9c9c0802381ad05f9e28bb/index.js#L33-L37

https://github.com/debute/laravel-mix-favicon/blob/13013f6ce5ff003d5f9c9c0802381ad05f9e28bb/index.js#L79-L83

**Comment by debute** [comment]
Thank you for noticing! I fixed it in 22a45e75fc9ffddec205bc18a5175e729af1cd54
